const env = process.env;

module.exports = {
    APP_NAME: env.APP_NAME,
    TELEGRAM_TOKEN: env.TELEGRAM_TOKEN,
    TELEGRAM_ID: env.TELEGRAM_ID,
    INTERVAL_CHECK_TIME: env.INTERVAL_CHECK_TIME,
    INTERVAL_REPORT_TIME: env.INTERVAL_REPORT_TIME,
    SILENT_MODE: env.SILENT_MODE === 'true'
}